name: deployWorkflow

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  build-firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@v4 # Equivalent à un clone sur la machine sous ubuntu-latest
      
      - name: installation des dépendances
        run: npm i

      - name: build firefox
        run: npm run build:firefox
      
      - name: Sign with web-ext
        run: |
          npx web-ext sign \
            --api-key ${{ secrets.AMO_JWT_ISSUER }} \
            --api-secret ${{ secrets.AMO_JWT_SECRET }} \
            --channel unlisted \
            --source-dir ./build \
            --artifacts-dir ./signed

      - name: create artefact
        run : npm run pack:zip
      
      - name: upload build artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          path: ./
